downgrading tree-sitter as new version breaks
because the `build_library` method was removed in a [recent
release](https://github.com/tree-sitter/py-tree-sitter/releases/tag/v0.22.0)
of py-tree-sitter, we now get
```
AttributeError: type object 'tree_sitter.Language' has no attribute 'build_library'
```